name       : KVIrc
version    : 5.0.0
release    : 1
source     :
    - https://github.com/grantdb/KVIrc/archive/5.0.tar.gz : 111d641af752b86265d9cf8a92146d9c159923245b868b234f91f4d007df8ce7
license    : GPLV2
component  : network.irc
summary    : The Visual IRC Client
description: |
    KVIrc is a free portable IRC client based on the excellent Qt GUI toolkit. http://www.kvirc.net/
builddeps  :
    - qt5-base-devel
    - qt5-multimedia-devel
    - qt5-webkit-devel
    - qt5-svg-devel
    - qt5-x11extras-devel
    - libx11
    - libdrm-devel
    - libglu-devel
    - phonon-devel
    - openssl-devel
    - perl
    - ncurses-devel
    - enchant-devel
    - gettext-devel
    - doxygen 
    - cmake 
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make install DESTDIR=/home/build/YPKG/root/KVIrc/install

