name       : KVIrc
version    : 4.9.3
release    : 1
source     :
    - https://github.com/grantdb/KVIrc/archive/4.9.tar.gz : d18eb073e0437ea9fb445586417c2d505026a681336c814966a28cb9fce55f7a
license    : GPLV2
component  : network.irc
summary    : The Visual IRC Client http://www.kvirc.net/
description: |
    KVIrc is a free portable IRC client based on the excellent Qt GUI toolkit.
builddeps  :
    - qt5-base-devel
    - qt5-multimedia-devel
    - qt5-webkit-devel
    - qt5-svg-devel
    - qt5-x11extras-devel
    - libx11
    - libdrm-devel
    - libglu-devel
    - phonon-devel
    - openssl-devel
    - perl
    - ncurses-devel
    - enchant-devel
    - gettext-devel
    - doxygen 
    - cmake 
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make install DESTDIR=/home/build/YPKG/root/KVIrc/install
