name       : PasswordSafe
version    : 1.04
release    : 4
source     : 
- https://github.com/grantdb/pwsafe/archive/39.tar.gz : 84b737bc36a6591226e5a74fb02e4ae13345cd5a096f28a754082077179e0806
license    : Artistic License 2.0
component  : security.crypto
summary    : Password Safe is a password database utility
description: |
    Simple & Secure Password Management. Designed by renowned security technologist Bruce Schneier https://pwsafe.org/
builddeps  :
    - wxwidgets-devel
    - fakeroot
    - g++
    - gettext-devel
    - qrencode-devel
    - xerces-c-devel
    - libxt-devel
    - libxtst-devel
    - zip
setup      : |
    %cmake -DNO_YUBI=1 -DNO_GTEST=1 .
build      : |
    %make
install    : |
    %make_install
